# Generated by Django 4.1.7 on 2023-03-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address1", models.CharField(max_length=500)),
                ("address2", models.CharField(max_length=500)),
                ("phone", models.CharField(max_length=20)),
                ("time", models.CharField(max_length=300)),
                ("email", models.EmailField(max_length=300)),
            ],
        ),
    ]
